### ISSUE TITLE
Works well - DockerRegistrySync?

### ISSUE THREAD

**Issue by wagnerscastle** [dr1rrb/docker-plex-win#2]
This works great on Windows Server and is much faster then a Hyper-V container.  Is there any chance you can add the source for DockerRegistrySync?  

Thank you!

**Comment by dr1rrb** [comment]
Hey @wagnerscastle thanks for your comment.

I've finally pushed the code of the DockerRegistrySync tool here: https://github.com/dr1rrb/docker-registry-sync (I just recovered it recently ... much better on github than on an old disk!)
