### ISSUE TITLE
The container operating system does not match the host operating system

### ISSUE THREAD

**Issue by ReenigneArcher** [dr1rrb/docker-plex-win#4]
I am attempting to use this image to test a Plex plugin in GitHub actions (https://github.com/LizardByte/Themerr-plex/pull/153). Is there any chance you could update your image to also support Windows Server?

```txt
docker: Error response from daemon: hcs::CreateComputeSystem c28381481df961b8fc89f0e0e97e52cff8826bf45c07090cfc87ba76ba0b6401: The container operating system does not match the host operating system.
Error 125 while starting the Plex docker container
```

This is probably related: https://stackoverflow.com/questions/55637682/pulling-a-windows-image-for-docker-on-windows-server-2019-has-os-compatibility-i

**Comment by ReenigneArcher** [comment]
I ended up bootstrapping a plex server in GitHub workflows using Chocolatey. Feel free to close this issue if you feel it's out of the project's scope.

**Comment by dr1rrb** [comment]
Hey @ReenigneArcher thanks for the report.

I'm currently on vacation, will try to have a look when I come back, but it's really in the scope of the project.
